name: Checks

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - uses: pnpm/action-setup@v2
              with:
                  version: 11

            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  pnpm install --no-verify-store-integrity || (rm -rf pnpm-lock.yaml && pnpm install --no-verify-store-integrity)

            - name: Run Prettier
              run: "pnpm run prettier"

            - name: Install library dependencies
              run: |
                  cd src && (pnpm install --no-verify-store-integrity || (rm -rf pnpm-lock.yaml && pnpm install --no-verify-store-integrity))

            - name: Compile library
              run: "cd src && pnpm run compile"

            - name: Check Types
              run: "pnpm run types"
